# Generated by Django 4.2 on 2023-10-25 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAYK', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
