# Generated by Django 4.2 on 2023-10-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAYK', '0002_alter_contacts_options_alter_price_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
    ]
