# Generated by Django 4.2 on 2023-10-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAYK', '0003_alter_contacts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='cena',
            field=models.CharField(max_length=10, verbose_name='Цена'),
        ),
    ]
